const key = 'entrada-app-v1';
const initial = {events:[{id:'evt-demo',name:'Noche de Jazz',date:'2026-10-10',time:'21:00',place:'Teatro Principal, Madrid',price:28,capacity:180}],sales:[]};
let data = JSON.parse(localStorage.getItem(key) || JSON.stringify(initial));
const $ = s => document.querySelector(s);
const money = n => new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(n);
const formatDate = d => new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(new Date(d+'T12:00'));
const save = () => localStorage.setItem(key,JSON.stringify(data));
function eventSales(id){return data.sales.filter(s=>s.eventId===id)}
function render(){
 const total = data.sales.reduce((a,s)=>a+s.quantity,0), amount=data.sales.reduce((a,s)=>a+s.total,0), checked=data.sales.reduce((a,s)=>a+s.checked,0);
 $('#tickets-sold').textContent=total; $('#revenue').textContent=money(amount); $('#checked-in').textContent=checked;
 $('#tickets-note').textContent=total?`${total} entradas emitidas`:'Aún no hay ventas'; $('#checkin-note').textContent=total?`${Math.round(checked/total*100)}% de las entradas`:'0% de las entradas';
 const upcoming=$('#upcoming-events'); upcoming.innerHTML=data.events.length?data.events.slice(0,4).map(e=>row(e)).join(''):'<p class="empty">Crea tu primer evento para empezar.</p>';
 const cards=$('#event-list'); cards.innerHTML=data.events.length?data.events.map(e=>card(e)).join(''):'<p class="empty">No hay eventos todavía.</p>';
 const sales=data.sales.slice().reverse(); $('#sales-list').innerHTML=sales.length?sales.map(s=>`<tr><td><strong>${esc(s.buyer)}</strong>${esc(s.email)}</td><td>${esc(findEvent(s.eventId)?.name||'Evento eliminado')}</td><td><code>${s.code}</code> × ${s.quantity}</td><td>${money(s.total)}</td><td><span class="status">Confirmada</span></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Todavía no se han emitido entradas.</td></tr>';
 $('#recent-sales').innerHTML=sales.length?sales.slice(0,5).map(s=>`<div class="activity-item"><strong>${esc(s.buyer)} compró ${s.quantity} entrada${s.quantity>1?'s':''}</strong><span>${esc(findEvent(s.eventId)?.name||'Evento')} · ${money(s.total)}</span></div>`).join(''):'<p class="empty">Las ventas aparecerán aquí.</p>';
}
function findEvent(id){return data.events.find(e=>e.id===id)}
function row(e){const d=new Date(e.date+'T12:00');return `<div class="event-row"><div class="date-badge"><b>${d.getDate()}</b><small>${d.toLocaleDateString('es-ES',{month:'short'}).replace('.','').toUpperCase()}</small></div><div><strong>${esc(e.name)}</strong><p>${formatDate(e.date)} · ${e.time} · ${esc(e.place)}</p></div><button class="sale-button" data-sell="${e.id}">Vender</button></div>`}
function card(e){const sold=eventSales(e.id).reduce((a,s)=>a+s.quantity,0);return `<article class="event-card"><div class="event-banner"><span>${formatDate(e.date).toUpperCase()} · ${e.time}</span><h3>${esc(e.name)}</h3></div><div class="event-body"><div class="event-info"><span>⌖ ${esc(e.place)}</span><strong>${money(e.price)}</strong></div><div>${sold} de ${e.capacity} entradas vendidas</div></div><footer><strong>${e.capacity-sold} disponibles</strong><div class="card-actions"><button class="delete-button" data-delete="${e.id}">Eliminar</button><button class="sale-button" data-sell="${e.id}">Vender entrada</button></div></footer></article>`}
function esc(v){const x=document.createElement('span');x.textContent=v;return x.innerHTML}
function show(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#page-title').textContent=view==='dashboard'?'Buenos días, organizador':view==='events'?'Gestiona tus eventos':view==='sales'?'Ventas y entradas':'Control de acceso';}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
function openEvent(){ $('#event-form').reset(); $('#event-form [name=date]').value=new Date().toISOString().slice(0,10); $('#event-modal').showModal() }
$('#new-event').onclick=openEvent; $('#new-event-2').onclick=openEvent;
$('#event-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);data.events.unshift({id:'evt-'+crypto.randomUUID(),name:f.get('name'),date:f.get('date'),time:f.get('time'),place:f.get('place'),price:+f.get('price'),capacity:+f.get('capacity')});save();$('#event-modal').close();render();show('events')});
document.addEventListener('click',e=>{const removeId=e.target.dataset.delete;if(removeId){const ev=findEvent(removeId),salesCount=eventSales(removeId).length;const warning=salesCount?` También se eliminarán ${salesCount} venta(s) vinculada(s).`:'';if(confirm(`¿Eliminar el evento “${ev.name}”? Esta acción no se puede deshacer.${warning}`)){data.events=data.events.filter(x=>x.id!==removeId);data.sales=data.sales.filter(x=>x.eventId!==removeId);save();render()}return}const id=e.target.dataset.sell;if(!id)return;const ev=findEvent(id),sold=eventSales(id).reduce((a,s)=>a+s.quantity,0);if(sold>=ev.capacity)return alert('Este evento está completo.');$('#sell-form').reset();$('#sell-form [name=eventId]').value=id;$('#sell-form [name=quantity]').max=ev.capacity-sold;$('#sell-event-name').textContent=ev.name;$('#sell-modal').showModal()});
$('#sell-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),ev=findEvent(f.get('eventId')),q=+f.get('quantity'),sold=eventSales(ev.id).reduce((a,s)=>a+s.quantity,0);if(q>ev.capacity-sold)return alert('No quedan suficientes entradas disponibles.');const sale={id:crypto.randomUUID(),eventId:ev.id,buyer:f.get('buyer'),email:f.get('email'),quantity:q,total:q*ev.price,checked:0,code:'ENT-'+Math.random().toString(36).slice(2,7).toUpperCase()};data.sales.push(sale);save();$('#sell-modal').close();render();$('#ticket-title').textContent=ev.name;$('#ticket-detail').textContent=`${sale.buyer} · ${formatDate(ev.date)} · ${ev.time}`;$('#ticket-id').textContent=sale.code;$('#ticket-modal').showModal()});
$('.ticket-close').onclick=()=>$('#ticket-modal').close();
$('#validate-ticket').onclick=()=>{const code=$('#ticket-code').value.trim().toUpperCase(), sale=data.sales.find(s=>s.code===code),out=$('#validation-result');if(!sale){out.innerHTML='<p class="empty">No encontramos una entrada con ese código.</p>';return}if(sale.checked>=sale.quantity){out.innerHTML='<p class="empty">Esta entrada ya fue validada en su totalidad.</p>';return}sale.checked++;save();render();out.innerHTML=`<div class="activity-item"><strong>✓ Entrada válida</strong><span>${esc(sale.buyer)} · ${esc(findEvent(sale.eventId).name)} · acceso ${sale.checked} de ${sale.quantity}</span></div>`;$('#ticket-code').value=''};
render();
